<?php

namespace Database\Seeders;

use App\Models\Alat;
use Illuminate\Database\Seeder;

class AlatSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // Total Station
            ['inventaris' => 'SGG/TS/001/2026', 'nama_alat' => 'Total Station', 'merk' => 'Nikon', 'tipe' => 'DTM-232', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_berat', 'jumlah' => 1, 'catatan' => [['komponen' => 'kabel data', 'keterangan' => 'putus']]]], 'lokasi_penyimpanan' => 'Lemari 5', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TS/002/2026', 'nama_alat' => 'Total Station', 'merk' => 'Nikon', 'tipe' => 'DTM-235', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_berat', 'jumlah' => 1, 'catatan' => [['komponen' => 'kabel data', 'keterangan' => 'putus'], ['komponen' => 'baterai', 'keterangan' => 'drop']]]], 'lokasi_penyimpanan' => 'Lemari 5', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TS/003/2026', 'nama_alat' => 'Total Station', 'merk' => 'Topcon', 'tipe' => 'GTS-1000', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_ringan', 'jumlah' => 1, 'catatan' => [['komponen' => 'baterai', 'keterangan' => 'drop']]]], 'lokasi_penyimpanan' => 'Lemari 5', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TS/004/2026', 'nama_alat' => 'Total Station', 'merk' => 'Ruide', 'tipe' => 'RQS', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_ringan', 'jumlah' => 1, 'catatan' => [['komponen' => 'baterai', 'keterangan' => 'penguci patah']]]], 'lokasi_penyimpanan' => 'Lemari 5', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TS/005/2026', 'nama_alat' => 'Total Station', 'merk' => 'Sokkia', 'tipe' => 'iM-50', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_ringan', 'jumlah' => 1, 'catatan' => [['komponen' => 'baterai', 'keterangan' => 'penguci patah']]]], 'lokasi_penyimpanan' => 'Lemari 5', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TS/006/2026', 'nama_alat' => 'Total Station', 'merk' => 'Sokkia', 'tipe' => 'iM-50', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_ringan', 'jumlah' => 1, 'catatan' => [['komponen' => 'baterai', 'keterangan' => 'penguci patah']]]], 'lokasi_penyimpanan' => 'Lemari 5', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TS/007/2026', 'nama_alat' => 'Total Station', 'merk' => 'Sokkia', 'tipe' => 'iM-50', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 4', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TS/008/2026', 'nama_alat' => 'Total Station', 'merk' => 'Sokkia', 'tipe' => 'iM-50', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 4', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TS/009/2026', 'nama_alat' => 'Total Station', 'merk' => 'Sokkia', 'tipe' => 'iM-50', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 4', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TS/010/2026', 'nama_alat' => 'Total Station', 'merk' => 'Sokkia', 'tipe' => 'iM-50', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 4', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TS/011/2026', 'nama_alat' => 'Total Station', 'merk' => 'Sokkia', 'tipe' => 'iM-50', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 4', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TS/012/2026', 'nama_alat' => 'Total Station', 'merk' => 'Sokkia', 'tipe' => 'iM-50', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 4', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TS/013/2026', 'nama_alat' => 'Total Station', 'merk' => 'Sokkia', 'tipe' => 'iM-50', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 4', 'ketersediaan' => 'tersedia'],
            // Sipat Datar
            ['inventaris' => 'SGG/WP/001/2026', 'nama_alat' => 'Sipat Datar', 'merk' => 'Titan', 'tipe' => 'TAL32', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_berat', 'jumlah' => 1, 'catatan' => [['komponen' => 'body', 'keterangan' => 'lepas']]]], 'lokasi_penyimpanan' => 'Lemari 4', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/WP/002/2026', 'nama_alat' => 'Sipat Datar', 'merk' => 'Titan', 'tipe' => 'TAL32', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 4', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/WP/003/2026', 'nama_alat' => 'Sipat Datar', 'merk' => 'Titan', 'tipe' => 'TAL32', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 4', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/WP/004/2026', 'nama_alat' => 'Sipat Datar', 'merk' => 'Topcon', 'tipe' => 'ATB-4A', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 4', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/WP/005/2026', 'nama_alat' => 'Sipat Datar', 'merk' => 'Topcon', 'tipe' => 'ATB-4A', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 4', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/WP/006/2026', 'nama_alat' => 'Sipat Datar', 'merk' => 'Sokkia', 'tipe' => 'B-40A', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 4', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/WP/007/2026', 'nama_alat' => 'Sipat Datar', 'merk' => 'Leica', 'tipe' => 'NA700', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 4', 'ketersediaan' => 'tersedia'],
            // Theodolite
            ['inventaris' => 'SGG/TH/001/2026', 'nama_alat' => 'Theodolite', 'merk' => 'Wild', 'tipe' => 'T0', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_berat', 'jumlah' => 1, 'catatan' => [['komponen' => 'nivo', 'keterangan' => 'tidak level']]]], 'lokasi_penyimpanan' => 'Lemari 3', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TH/002/2026', 'nama_alat' => 'Theodolite', 'merk' => 'Wild', 'tipe' => 'T0', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_berat', 'jumlah' => 1, 'catatan' => [['komponen' => 'nivo', 'keterangan' => 'tidak level']]]], 'lokasi_penyimpanan' => 'Lemari 3', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TH/003/2026', 'nama_alat' => 'Theodolite', 'merk' => 'Wild', 'tipe' => 'T0', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_berat', 'jumlah' => 1, 'catatan' => [['komponen' => 'nivo', 'keterangan' => 'tidak level']]]], 'lokasi_penyimpanan' => 'Lemari 3', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TH/004/2026', 'nama_alat' => 'Theodolite', 'merk' => 'Sokkisha', 'tipe' => 'TM-20E', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 3', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TH/005/2026', 'nama_alat' => 'Theodolite', 'merk' => 'Sokkisha', 'tipe' => 'TM-20E', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_ringan', 'jumlah' => 1, 'catatan' => [['komponen' => 'centering optis', 'keterangan' => 'buram'], ['komponen' => 'nivo', 'keterangan' => 'tidak level'], ['komponen' => 'pengunci', 'keterangan' => 'loss']]]], 'lokasi_penyimpanan' => 'Lemari 3', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TH/006/2026', 'nama_alat' => 'Theodolite', 'merk' => 'Sokkisha', 'tipe' => 'TM6', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_berat', 'jumlah' => 1, 'catatan' => [['komponen' => 'centering optis', 'keterangan' => 'buram'], ['komponen' => 'nivo', 'keterangan' => 'tidak level'], ['komponen' => 'pengunci', 'keterangan' => 'loss']]]], 'lokasi_penyimpanan' => 'Lemari 3', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TH/007/2026', 'nama_alat' => 'Theodolite', 'merk' => 'Sokkisha', 'tipe' => 'TM6', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_berat', 'jumlah' => 1, 'catatan' => [['komponen' => 'centering optis', 'keterangan' => 'buram'], ['komponen' => 'nivo', 'keterangan' => 'tidak level'], ['komponen' => 'pengunci', 'keterangan' => 'loss']]]], 'lokasi_penyimpanan' => 'Lemari 3', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TH/008/2026', 'nama_alat' => 'Theodolite', 'merk' => 'Sokkisha', 'tipe' => 'TM6', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_berat', 'jumlah' => 1, 'catatan' => [['komponen' => 'centering optis', 'keterangan' => 'buram'], ['komponen' => 'nivo', 'keterangan' => 'tidak level'], ['komponen' => 'pengunci', 'keterangan' => 'loss']]]], 'lokasi_penyimpanan' => 'Lemari 3', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TH/009/2026', 'nama_alat' => 'Theodolite', 'merk' => 'Sokkisha', 'tipe' => 'TM6', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_berat', 'jumlah' => 1, 'catatan' => [['komponen' => 'centering optis', 'keterangan' => 'buram'], ['komponen' => 'nivo', 'keterangan' => 'tidak level'], ['komponen' => 'pengunci', 'keterangan' => 'loss']]]], 'lokasi_penyimpanan' => 'Lemari 3', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TH/010/2026', 'nama_alat' => 'Theodolite', 'merk' => 'Topcon', 'tipe' => 'TL-6E', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 3', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TH/011/2026', 'nama_alat' => 'Theodolite', 'merk' => 'Topcon', 'tipe' => 'TL-6E', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_berat', 'jumlah' => 1, 'catatan' => [['komponen' => 'centering optis', 'keterangan' => 'buram'], ['komponen' => 'nivo', 'keterangan' => 'tidak level'], ['komponen' => 'pengunci', 'keterangan' => 'loss']]]], 'lokasi_penyimpanan' => 'Lemari 3', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/TH/012/2026', 'nama_alat' => 'Theodolite', 'merk' => 'Topcon', 'tipe' => 'TL-6E', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_berat', 'jumlah' => 1, 'catatan' => [['komponen' => 'centering optis', 'keterangan' => 'buram'], ['komponen' => 'nivo', 'keterangan' => 'tidak level'], ['komponen' => 'pengunci', 'keterangan' => 'loss']]]], 'lokasi_penyimpanan' => 'Lemari 3', 'ketersediaan' => 'tersedia'],
            // GNSS Geodetik
            ['inventaris' => 'SGG/GNSS/001/2026', 'nama_alat' => 'GNSS Geodetik', 'merk' => 'ComNav', 'tipe' => 'T300', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'rusak_ringan', 'jumlah' => 1, 'catatan' => [['komponen' => 'perekaman', 'keterangan' => 'sering gagal']]]], 'lokasi_penyimpanan' => 'Lemari 1', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/GNSS/002/2026', 'nama_alat' => 'GNSS Geodetik', 'merk' => 'ComNav', 'tipe' => 'T300', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 1', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/GNSS/003/2026', 'nama_alat' => 'GNSS Geodetik', 'merk' => 'CHCNAV', 'tipe' => 'iBase', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 1', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/GNSS/004/2026', 'nama_alat' => 'GNSS Geodetik', 'merk' => 'CHCNAV', 'tipe' => 'i76', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 1', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/GNSS/005/2026', 'nama_alat' => 'GNSS Geodetik', 'merk' => 'CHCNAV', 'tipe' => 'i76', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 1', 'ketersediaan' => 'tersedia'],
            ['inventaris' => 'SGG/GNSS/006/2026', 'nama_alat' => 'GNSS Geodetik', 'merk' => 'CHCNAV', 'tipe' => 'i76', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 1', 'ketersediaan' => 'tersedia'],
            // Statif
            ['inventaris' => 'SGG/STF/001/2026', 'nama_alat' => 'Statif', 'merk' => 'Sokkia', 'tipe' => 'Alumunium', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 2', 'ketersediaan' => 'tersedia'],
            // Extend Pole
            ['inventaris' => 'SGG/POL/001/2026', 'nama_alat' => 'Extend Pole', 'merk' => 'Sokkia', 'tipe' => 'Alumunium', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 2', 'ketersediaan' => 'tersedia'],
            // Prisma
            ['inventaris' => 'SGG/PRS/001/2026', 'nama_alat' => 'Prisma', 'merk' => 'Sokkia', 'tipe' => '30mm', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 2', 'ketersediaan' => 'tersedia'],
            // Plat Prisma
            ['inventaris' => 'SGG/PLT/001/2026', 'nama_alat' => 'Plat Prisma', 'merk' => 'Sokkia', 'tipe' => '30mm', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 2', 'ketersediaan' => 'tersedia'],
            // Rambu Ukur
            ['inventaris' => 'SGG/RMB/001/2026', 'nama_alat' => 'Rambu Ukur', 'merk' => 'Myzox', 'tipe' => '3 meter', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 2', 'ketersediaan' => 'tersedia'],
            // Tribrach
            ['inventaris' => 'SGG/TRB/001/2026', 'nama_alat' => 'Tribrach', 'merk' => 'HD', 'tipe' => '19', 'serial_number' => '-', 'jumlah' => 1, 'kondisi' => [['status' => 'baik', 'jumlah' => 1, 'catatan' => []]], 'lokasi_penyimpanan' => 'Lemari 2', 'ketersediaan' => 'tersedia'],
        ];

        foreach ($data as $item) {
            Alat::updateOrCreate(
                ['inventaris' => $item['inventaris']],
                $item
            );
        }
    }
}
